
package edu.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IBGEServiceImplementService", targetNamespace = "http://soap.edu/", wsdlLocation = "http://localhost:8080/ibge?wsdl")
public class IBGEServiceImplementService
    extends Service
{

    private final static URL IBGESERVICEIMPLEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException IBGESERVICEIMPLEMENTSERVICE_EXCEPTION;
    private final static QName IBGESERVICEIMPLEMENTSERVICE_QNAME = new QName("http://soap.edu/", "IBGEServiceImplementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ibge?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IBGESERVICEIMPLEMENTSERVICE_WSDL_LOCATION = url;
        IBGESERVICEIMPLEMENTSERVICE_EXCEPTION = e;
    }

    public IBGEServiceImplementService() {
        super(__getWsdlLocation(), IBGESERVICEIMPLEMENTSERVICE_QNAME);
    }

    public IBGEServiceImplementService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IBGESERVICEIMPLEMENTSERVICE_QNAME, features);
    }

    public IBGEServiceImplementService(URL wsdlLocation) {
        super(wsdlLocation, IBGESERVICEIMPLEMENTSERVICE_QNAME);
    }

    public IBGEServiceImplementService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IBGESERVICEIMPLEMENTSERVICE_QNAME, features);
    }

    public IBGEServiceImplementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IBGEServiceImplementService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IBGEService
     */
    @WebEndpoint(name = "IBGEServiceImplementPort")
    public IBGEService getIBGEServiceImplementPort() {
        return super.getPort(new QName("http://soap.edu/", "IBGEServiceImplementPort"), IBGEService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBGEService
     */
    @WebEndpoint(name = "IBGEServiceImplementPort")
    public IBGEService getIBGEServiceImplementPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.edu/", "IBGEServiceImplementPort"), IBGEService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IBGESERVICEIMPLEMENTSERVICE_EXCEPTION!= null) {
            throw IBGESERVICEIMPLEMENTSERVICE_EXCEPTION;
        }
        return IBGESERVICEIMPLEMENTSERVICE_WSDL_LOCATION;
    }

}
