
package edu.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IBGEService", targetNamespace = "http://soap.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IBGEService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEstado", targetNamespace = "http://soap.edu/", className = "edu.soap.GetEstado")
    @ResponseWrapper(localName = "getEstadoResponse", targetNamespace = "http://soap.edu/", className = "edu.soap.GetEstadoResponse")
    @Action(input = "http://soap.edu/IBGEService/getEstadoRequest", output = "http://soap.edu/IBGEService/getEstadoResponse")
    public String getEstado(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "teste", targetNamespace = "http://soap.edu/", className = "edu.soap.Teste")
    @ResponseWrapper(localName = "testeResponse", targetNamespace = "http://soap.edu/", className = "edu.soap.TesteResponse")
    @Action(input = "http://soap.edu/IBGEService/testeRequest", output = "http://soap.edu/IBGEService/testeResponse")
    public String teste();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMunicipio", targetNamespace = "http://soap.edu/", className = "edu.soap.GetMunicipio")
    @ResponseWrapper(localName = "getMunicipioResponse", targetNamespace = "http://soap.edu/", className = "edu.soap.GetMunicipioResponse")
    @Action(input = "http://soap.edu/IBGEService/getMunicipioRequest", output = "http://soap.edu/IBGEService/getMunicipioResponse")
    public String getMunicipio(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "estados", targetNamespace = "http://soap.edu/", className = "edu.soap.Estados")
    @ResponseWrapper(localName = "estadosResponse", targetNamespace = "http://soap.edu/", className = "edu.soap.EstadosResponse")
    @Action(input = "http://soap.edu/IBGEService/estadosRequest", output = "http://soap.edu/IBGEService/estadosResponse")
    public String estados();

}
